import { FoodItem, PriceLevel } from './types';

export const INITIAL_FOODS: FoodItem[] = [
  {
    id: '101',
    imageNo: 101,
    name: '御陕坊猪头肉 & 山东水饺',
    location: '御陕坊/山东水饺',
    campusLocation: '校外',
    specificPrice: '¥22 / ¥17',
    priceLevel: PriceLevel.MODERATE,
    tags: ['小吃', '面食', '辣', '聚餐', '外卖'],
    postDate: '01-08',
    originalUrl: 'https://www.xiaohongshu.com/explore/695f8348000000001a036167',
    originalPost: '猪头肉非常软烂！猪肝香香的，麻辣香肠香香辣辣。饺子蘸拌菜的汤汁也好绝啊。',
    recommendationIndex: 9.5,
    rating: 4.8
  },
  {
    id: '102',
    imageNo: 102,
    name: '云南特色简餐/咖啡',
    location: '云南咖啡店',
    campusLocation: '校内',
    canteen: '其他',
    tags: ['咖啡', '甜点', '西餐', '清淡', '一人食'],
    postDate: '2025-12-01',
    originalUrl: 'https://www.xiaohongshu.com/explore/692d0e15000000001e02b2c9',
    originalPost: '环境很漂亮！不算大但很精致。感觉很适合点饮料和小蛋糕然后坐在这边自习。',
    recommendationIndex: 8.0,
    priceLevel: PriceLevel.MODERATE,
    rating: 4.0
  },
  {
    id: '103',
    imageNo: 103,
    name: '红旗羊肉',
    location: '红旗羊肉',
    campusLocation: '校外',
    specificPrice: '人均 ¥60',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['火锅', '羊肉', '聚餐', '面食', '养生', '夜宵'],
    postDate: '2025-03-09',
    originalUrl: 'https://www.xiaohongshu.com/explore/67cdacea000000002902c356',
    originalPost: '这家羊肉真的好好吃，肉炖的软烂，很香但一点都不膻。葱油拌面也很便宜很好吃。',
    recommendationIndex: 9.2,
    rating: 4.6
  },
  {
    id: '104',
    imageNo: 104,
    name: '二餐石锅鸡',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥15',
    priceLevel: PriceLevel.CHEAP,
    tags: ['米饭', '辣', '一人食', '快餐'],
    postDate: '2025-11-26',
    originalUrl: 'https://www.xiaohongshu.com/explore/69253bc6000000001e036ca5',
    originalPost: '汤底香香辣辣的！炸蛋蘸满汤汁绝了太美味。里面加泡面的简直天才行为。',
    recommendationIndex: 9.0,
    rating: 4.5
  },
  {
    id: '105',
    imageNo: 105,
    name: '牛new大闸蟹自助',
    location: '牛new',
    campusLocation: '校外',
    tags: ['火锅', '自助', '聚餐', '海鲜', '日料'],
    postDate: '2025-10-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/68fc7a9c0000000004000850',
    originalPost: '大闸蟹吃到腻了！2.5两母蟹个个满黄！大块蟹黄沾点蟹醋香绝了。',
    recommendationIndex: 9.5,
    priceLevel: PriceLevel.EXPENSIVE,
    rating: 4.8
  },
  {
    id: '106',
    imageNo: 106,
    name: '二餐辛拉面',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥14',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '韩式', '一人食', '速食'],
    postDate: '2025-12-12',
    originalUrl: 'https://www.xiaohongshu.com/explore/693c34a9000000001e0276c9',
    originalPost: '好吃但性价比低。汤底是香香的，介于清淡和醇厚之间。感觉很适合冷冷的天气吃。',
    recommendationIndex: 7.5,
    rating: 3.8
  },
  {
    id: '107',
    imageNo: 107,
    name: '四餐大棒骨',
    location: '四餐二楼农家菜',
    campusLocation: '校内',
    canteen: '四餐',
    specificPrice: '¥18',
    priceLevel: PriceLevel.CHEAP,
    tags: ['家常菜', '米饭', '一人食', '清淡'],
    postDate: '2025-10-27',
    originalUrl: 'https://www.xiaohongshu.com/explore/68ff396d0000000004010342',
    originalPost: '巨大一个骨头棒，汤喝起来鲜鲜的。大骨头上面有很多肉，炖的烂烂的一点都不柴。',
    recommendationIndex: 8.8,
    rating: 4.4
  },
  {
    id: '108',
    imageNo: 108,
    name: '俏传奇地锅鸡',
    location: '宝龙附近',
    campusLocation: '校外',
    specificPrice: '人均 ¥60',
    priceLevel: PriceLevel.MODERATE,
    tags: ['火锅', '聚餐', '辣', '家常菜'],
    postDate: '2025-11-22',
    originalUrl: 'https://www.xiaohongshu.com/explore/69214eff000000001e037d5f',
    originalPost: '现场爆炒后炖煮，掀开锅盖香迷糊了！肉咸咸香香的超软烂入味！饼底脆脆的口感好好。',
    recommendationIndex: 8.5,
    rating: 4.3
  },
  {
    id: '109',
    imageNo: 109,
    name: '二餐土豆泥拌饭',
    location: '二餐西餐厅',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥15',
    priceLevel: PriceLevel.CHEAP,
    tags: ['西餐', '米饭', '一人食'],
    postDate: '2025-12-27',
    originalUrl: 'https://www.xiaohongshu.com/explore/694f810f000000001f006fe0',
    originalPost: '很多土豆泥，和饭拌在一起香喷喷软绵绵的。鸡排中规中矩，但饭真的很好吃！',
    recommendationIndex: 8.2,
    rating: 4.1
  },
  {
    id: '110',
    imageNo: 110,
    name: '海底捞番茄汤虾滑捞饭',
    location: '外卖',
    campusLocation: '校外',
    specificPrice: '¥29',
    priceLevel: PriceLevel.MODERATE,
    tags: ['外卖', '火锅', '米饭', '一人食'],
    postDate: '2025-10-03',
    originalUrl: 'https://www.xiaohongshu.com/explore/68dfa2bb000000000400632b',
    originalPost: '爱喝海底捞番茄汤的本人大满足。虾滑超大颗好好吃！香绝了好吗。',
    recommendationIndex: 9.0,
    rating: 4.5
  },
  {
    id: '111',
    imageNo: 111,
    name: '玉兰苑冰淇淋菠萝包',
    location: '玉兰苑',
    campusLocation: '校内',
    canteen: '玉兰苑',
    specificPrice: '¥8',
    priceLevel: PriceLevel.CHEAP,
    tags: ['甜点', '小吃', '一人食'],
    postDate: '2025-09-21',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d0171f000000000b03c3b6',
    originalPost: '热乎乎的菠萝包夹着凉丝丝的冰淇淋。酥皮的微咸、面包的麦香和甜甜凉凉的冰淇淋配在一起好好吃🤤。',
    recommendationIndex: 8.5,
    rating: 4.3
  },
  {
    id: '112',
    imageNo: 112,
    name: '二餐奥利奥鸡蛋仔',
    location: '二餐一楼 (轻甜茶季)',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥16',
    priceLevel: PriceLevel.CHEAP,
    tags: ['甜点', '小吃', '一人食'],
    postDate: '2025-11-27',
    originalUrl: 'https://www.xiaohongshu.com/explore/69272980000000001e0340ae',
    originalPost: '鸡蛋仔好好吃啊，蘸上冰淇淋香香甜甜的。冰淇淋是冰感有点强的那种，好处是不腻。',
    recommendationIndex: 8.0,
    rating: 4.0
  },
  {
    id: '113',
    imageNo: 113,
    name: '成都巷子水煮鱼',
    location: '剑川路',
    campusLocation: '校外',
    specificPrice: '人均 ¥70',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['川菜', '鱼', '聚餐', '辣', '火锅'],
    postDate: '2025-05-28',
    originalUrl: 'https://www.xiaohongshu.com/explore/68367c2000000000210055c4',
    originalPost: '鱼是现杀的黑鱼，很新鲜。锅底巨香啊！点了微辣，有淡淡的麻感很上头。配菜浸满汤汁好好吃。',
    recommendationIndex: 9.0,
    rating: 4.5
  },
  {
    id: '114',
    imageNo: 114,
    name: '储牛香潮汕牛肉火锅',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '人均 ¥100',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['火锅', '潮汕菜', '牛肉', '聚餐', '清淡'],
    postDate: '2025-12-08',
    originalUrl: 'https://www.xiaohongshu.com/explore/6927e624000000001e0279dc',
    originalPost: '肉都是鲜切的，超新鲜。裹满沙茶酱香绝了，吃牛肉火锅必须配沙茶酱！炒饭也超好吃，锅气好足。',
    recommendationIndex: 9.5,
    rating: 4.8
  },
  {
    id: '115',
    imageNo: 115,
    name: '一餐红枣桂圆鸡',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥16',
    priceLevel: PriceLevel.CHEAP,
    tags: ['家常菜', '养生', '一人食', '清淡'],
    postDate: '2025-11-23',
    originalUrl: 'https://www.xiaohongshu.com/explore/6922ea6b000000001e02ef2f',
    originalPost: '暖暖的鸡汤太适合寒冷冬天！依然是大大的鸡腿，热乎乎香香的汤底。鸡腿的肉很软烂一点都不柴。',
    recommendationIndex: 8.5,
    rating: 4.3
  },
  {
    id: '116',
    imageNo: 116,
    name: '陈香贵番茄牛骨面',
    location: '陈香贵',
    campusLocation: '校外',
    specificPrice: '¥20',
    priceLevel: PriceLevel.MODERATE,
    tags: ['面食', '快餐', '一人食', '外卖', '西北菜'],
    postDate: '2025-03-20',
    originalUrl: 'https://www.xiaohongshu.com/explore/67daea06000000001d0266ac',
    originalPost: '番茄牛骨汤面好吃啊，有点像海底捞番茄锅的味道。除了浓郁的番茄酱还加了新鲜番茄，汤也好喝。',
    recommendationIndex: 8.0,
    rating: 4.0
  },
  {
    id: '117',
    imageNo: 117,
    name: '牛new甜品测评',
    location: '牛new',
    campusLocation: '校外',
    tags: ['甜点', '自助', '聚餐'],
    postDate: '2024-10-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/66225be70000000001032cd6',
    originalPost: '好吃推荐：焦糖布丁、巴斯克、萄你欢心。难吃预警：可可泡芙、樱花味慕斯。',
    recommendationIndex: 7.0,
    priceLevel: PriceLevel.MODERATE,
    rating: 3.5
  },
  {
    id: '118',
    imageNo: 118,
    name: '西贝小炒牛肉套餐',
    location: '外卖',
    campusLocation: '校外',
    specificPrice: '¥20',
    priceLevel: PriceLevel.MODERATE,
    tags: ['外卖', '西北菜', '辣', '家常菜', '米饭'],
    postDate: '2025-11-07',
    originalUrl: 'https://www.xiaohongshu.com/explore/690d813f0000000005033dfc',
    originalPost: '牛肉很好吃！嫩嫩的辣辣的很下饭。豆腐汤好喝！很鲜！加黄馍馍不到20。',
    recommendationIndex: 8.5,
    rating: 4.3
  },
  {
    id: '119',
    imageNo: 119,
    name: '二餐三楼徽三鲜',
    location: '二餐三楼',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥13',
    priceLevel: PriceLevel.CHEAP,
    tags: ['家常菜', '清淡', '一人食', '米饭'],
    postDate: '2025-11-04',
    originalUrl: 'https://www.xiaohongshu.com/explore/690973f00000000004015126',
    originalPost: '汤底味道很鲜，内容很丰富（鸡丝酥肉蛋饺）。适合没什么胃口的时候吃。',
    recommendationIndex: 7.5,
    rating: 3.8
  },
  {
    id: '120',
    imageNo: 120,
    name: '思源门外河北炒饼',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '¥16',
    priceLevel: PriceLevel.CHEAP,
    tags: ['外卖', '面食', '辣', '小吃'],
    postDate: '2025-10-29',
    originalUrl: 'https://www.xiaohongshu.com/explore/6901f7ac000000000400352b',
    originalPost: '很好吃！锅气十足，香香辣辣的。配料有鸡蛋豆芽包菜培根等。',
    recommendationIndex: 8.2,
    rating: 4.1
  },
  {
    id: '121',
    imageNo: 121,
    name: '四餐鸭血粉丝汤',
    location: '四餐二楼',
    campusLocation: '校内',
    canteen: '四餐',
    specificPrice: '¥17',
    priceLevel: PriceLevel.CHEAP,
    tags: ['小吃', '面食', '一人食'],
    postDate: '2025-10-28',
    originalUrl: 'https://www.xiaohongshu.com/explore/6900ad1c000000000500214f',
    originalPost: '汤的味道很浓郁很好喝！鸭血以及各种鸭杂也好吃。搭配的饼酥酥脆脆。',
    recommendationIndex: 8.0,
    rating: 4.0
  },
  {
    id: '122',
    imageNo: 122,
    name: '一餐大盘鸡面',
    location: '一餐民族餐厅',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['面食', '清真', '辣'],
    postDate: '2024-03-09',
    originalUrl: 'https://www.xiaohongshu.com/explore/65ec3a0f000000000102baa0',
    originalPost: '面是当场制作的，口感筋道。土豆软糯。去的时候人多需要排队。',
    recommendationIndex: 8.4,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.2
  },
  {
    id: '123',
    imageNo: 123,
    name: '大田大排面青椒肉丝拌面',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '¥17.8',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '一人食', '外卖', '家常菜'],
    postDate: '2025-09-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d55fcb000000000b03f81b',
    originalPost: '现炒的青椒肉丝，肉很嫩很入味。酱和面拌在一起绝了，浓郁的酱香裹满面条。',
    recommendationIndex: 9.5,
    rating: 4.8
  },
  {
    id: '124',
    imageNo: 124,
    name: '五餐菌菇鸡汤饭',
    location: '五餐二楼',
    campusLocation: '校内',
    canteen: '五餐',
    specificPrice: '¥16',
    priceLevel: PriceLevel.CHEAP,
    tags: ['米饭', '养生', '清淡'],
    postDate: '2025-09-24',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d3ea82000000000e00d48c',
    originalPost: '鸡汤很鲜，没有科技感。鸡肉不柴。适合清淡饮食阶段选择暖呼呼的。',
    recommendationIndex: 7.8,
    rating: 3.9
  },
  {
    id: '125',
    imageNo: 125,
    name: '东坡肉焗饭',
    location: '外卖',
    campusLocation: '校外',
    tags: ['外卖', '米饭', '家常菜', '快餐'],
    postDate: '2025-09-23',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d29862000000000e030d65',
    originalPost: '巨巨巨好吃！东坡肉软烂。虽然非常油，但饿的时候总会很想吃。',
    recommendationIndex: 8.2,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.1
  },
  {
    id: '126',
    imageNo: 126,
    name: '桂山禾桂林卤粉',
    location: '桂山禾',
    campusLocation: '校内',
    canteen: '其他',
    specificPrice: '¥24',
    priceLevel: PriceLevel.MODERATE,
    tags: ['面食', '辣', '一人食'],
    postDate: '2025-09-22',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d16995000000000b010e98',
    originalPost: '锅烧太好吃了皮酥酥脆脆的，肉的部分一点都不柴。卤汁拌开滑溜溜。',
    recommendationIndex: 8.5,
    rating: 4.3
  },
  {
    id: '127',
    imageNo: 127,
    name: '三餐一楼擂椒饭',
    location: '三餐一楼',
    campusLocation: '校内',
    canteen: '三餐',
    specificPrice: '¥19',
    priceLevel: PriceLevel.CHEAP,
    tags: ['米饭', '辣', '一人食'],
    postDate: '2025-09-21',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d012f9000000000e02727b',
    originalPost: '小炒牛肉拼辣子鸡，非常下饭，香香辣辣。提醒：擂椒非常辣。',
    recommendationIndex: 8.0,
    rating: 4.0
  },
  {
    id: '128',
    imageNo: 128,
    name: '食野轻食荞麦面',
    location: '食野轻食',
    campusLocation: '校外',
    specificPrice: '¥12',
    priceLevel: PriceLevel.CHEAP,
    tags: ['轻食', '外卖', '清淡', '一人食', '减脂'],
    postDate: '2025-09-23',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d22e89000000000e00e2e2',
    originalPost: '荞麦面口感清爽，外卖送来不黏不坨。南瓜甜甜绵密的口感很好。',
    recommendationIndex: 8.2,
    rating: 4.1
  },
  {
    id: '129',
    imageNo: 129,
    name: '二餐麻酱拌面',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥12',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '便宜', '一人食'],
    postDate: '2025-09-06',
    originalUrl: 'https://www.xiaohongshu.com/explore/68bc4852000000001c0304da',
    originalPost: '酱很香，拌好之后软软糯糯口感很好。可惜加点的大排柴且不入味。',
    recommendationIndex: 7.2,
    rating: 3.6
  },
  {
    id: '130',
    imageNo: 130,
    name: '渝辣度重庆小面',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '¥25',
    priceLevel: PriceLevel.MODERATE,
    tags: ['面食', '辣', '川菜', '小吃'],
    postDate: '2025-09-05',
    originalUrl: 'https://www.xiaohongshu.com/explore/68baee17000000001c031ca6',
    originalPost: '肥肠拌面好吃！比汤面味道更浓郁，酱料裹在面条上香辣过瘾。',
    recommendationIndex: 8.5,
    rating: 4.3
  },
  {
    id: '131',
    imageNo: 131,
    name: '一餐一楼牛杂粉丝汤',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥15',
    priceLevel: PriceLevel.CHEAP,
    tags: ['小吃', '辣', '一人食'],
    postDate: '2025-05-26',
    originalUrl: 'https://www.xiaohongshu.com/explore/683472b40000000021008916',
    originalPost: '粉丝滑滑的，牛杂香香的，萝卜软烂入味。汤底多了一点香辣，很舒适。',
    recommendationIndex: 8.1,
    rating: 4.1
  },
  {
    id: '132',
    imageNo: 132,
    name: '觅南洋马来小馆',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '人均 ¥100',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['东南亚菜', '聚餐', '西餐', '清淡'],
    postDate: '2025-05-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/683307920000000022004661',
    originalPost: '海南鸡嫩嫩的配酱很美妙。冬阴功汤开胃。环境有氛围，适合姐妹聊天。',
    recommendationIndex: 8.0,
    rating: 4.0
  },
  {
    id: '133',
    imageNo: 133,
    name: '正宗川菜馆',
    location: '沧源路',
    campusLocation: '校外',
    specificPrice: '¥45',
    priceLevel: PriceLevel.MODERATE,
    tags: ['川菜', '辣', '聚餐', '家常菜'],
    postDate: '2025-08-30',
    originalUrl: 'https://www.xiaohongshu.com/explore/682d8e7a00000000220052da',
    originalPost: '毛血旺食材丰富下饭。店面干净，量很大，两人吃不完。微辣度适中。',
    recommendationIndex: 8.8,
    rating: 4.4
  },
  {
    id: '134',
    imageNo: 134,
    name: '沪小烤自助烧烤',
    location: '景西路地铁站',
    campusLocation: '校外',
    specificPrice: '人均 ¥60',
    priceLevel: PriceLevel.MODERATE,
    tags: ['烧烤', '聚餐', '自助', '夜宵'],
    postDate: '2025-05-24',
    originalUrl: 'https://www.xiaohongshu.com/explore/6831b67c000000002101a329',
    originalPost: '自选菜品，自助烧烤过程有趣。肉挺新鲜，过程很治愈但味道受技术限制。',
    recommendationIndex: 7.5,
    rating: 3.8
  },
  {
    id: '135',
    imageNo: 135,
    name: '罗森汉堡雪糕',
    location: '罗森',
    campusLocation: '校内',
    canteen: '其他',
    specificPrice: '¥12.9',
    priceLevel: PriceLevel.CHEAP,
    tags: ['甜点', '小吃', '快餐'],
    postDate: '2025-05-13',
    originalUrl: 'https://www.xiaohongshu.com/explore/682303e7000000002100978e',
    originalPost: '咸黄油味，口感奇妙包含糯米片。味道一般但长得好玩。',
    recommendationIndex: 6.0,
    rating: 3.0
  },
  {
    id: '136',
    imageNo: 136,
    name: '玉兰面包梦龙脏脏包',
    location: '玉兰苑',
    campusLocation: '校内',
    canteen: '玉兰苑',
    specificPrice: '¥13.5',
    priceLevel: PriceLevel.CHEAP,
    tags: ['甜点', '面包'],
    postDate: '2025-04-21',
    originalUrl: 'https://www.xiaohongshu.com/explore/6806610f000000001d025eb2',
    originalPost: '巧克力味浓郁但不苦。蛋糕细腻奶油量大。一个人吃略大，容易腻。',
    recommendationIndex: 8.2,
    rating: 4.1
  },
  {
    id: '137',
    imageNo: 137,
    name: '交环创咖茉莉乌龙冰淇淋',
    location: '环境学院',
    campusLocation: '校内',
    canteen: '其他',
    specificPrice: '¥3',
    priceLevel: PriceLevel.CHEAP,
    tags: ['甜点', '冰淇淋', '便宜', '清淡'],
    postDate: '2025-04-18',
    originalUrl: 'https://www.xiaohongshu.com/explore/68025529000000001d02eb50',
    originalPost: '花茶味淡淡的清香，口感清爽不容易腻。只需3块，甜筒阿芙佳朵都赞。',
    recommendationIndex: 9.0,
    rating: 4.5
  },
  {
    id: '138',
    imageNo: 138,
    name: '一餐牛肉汤泡饼',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥16',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '汤', '清淡'],
    postDate: '2025-04-16',
    originalUrl: 'https://www.xiaohongshu.com/explore/67ff0e36000000001c00d6d7',
    originalPost: '牛肉汤味道醇正，配上饼丝很香。建议边泡边吃防止过软。',
    recommendationIndex: 8.5,
    rating: 4.3
  },
  {
    id: '139',
    imageNo: 139,
    name: '罗森甜辣炒年糕',
    location: '罗森',
    campusLocation: '校内',
    canteen: '其他',
    specificPrice: '¥13.8',
    priceLevel: PriceLevel.CHEAP,
    tags: ['小吃', '快餐', '辣', '韩式'],
    postDate: '2025-03-11',
    originalUrl: 'https://www.xiaohongshu.com/explore/67d02bb30000000028035636',
    originalPost: '糯叽叽星人狂喜，又甜又辣。比炸鸡店的好吃，微波炉加热很香。',
    recommendationIndex: 8.8,
    rating: 4.4
  },
  {
    id: '140',
    imageNo: 140,
    name: '罗森鸡腿雪糕',
    location: '罗森',
    campusLocation: '校内',
    canteen: '其他',
    specificPrice: '¥9.9',
    priceLevel: PriceLevel.CHEAP,
    tags: ['甜点', '小吃', '快餐'],
    postDate: '2025-03-10',
    originalUrl: 'https://www.xiaohongshu.com/explore/67cf0299000000002503cc66',
    originalPost: '外形酷似鸡腿，壳脆雪糕香。甚至“骨头”是饼干做的，好玩又好吃。',
    recommendationIndex: 7.5,
    rating: 3.8
  },
  {
    id: '141',
    imageNo: 141,
    name: '玉兰苑蛋炒刀削面',
    location: '玉兰苑',
    campusLocation: '校内',
    canteen: '玉兰苑',
    specificPrice: '¥14',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '快餐'],
    postDate: '2025-01-01',
    originalUrl: 'https://www.xiaohongshu.com/explore/6775634500000000130186c8',
    originalPost: '浓郁番茄和鸡蛋香，锅气足。刀削面筋道。吃到最后略咸。',
    recommendationIndex: 8.6,
    rating: 4.3
  },
  {
    id: '142',
    imageNo: 142,
    name: '思源门外插花牛肉粉',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '¥12.9',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '清淡', '小吃'],
    postDate: '2025-03-09',
    originalUrl: 'https://www.xiaohongshu.com/explore/67cdab63000000002802bf2e',
    originalPost: '汤底香醇好喝，牛肉嫩。粉可以免费续。适合想要清淡饮食的时刻。',
    recommendationIndex: 8.2,
    rating: 4.1
  },
  {
    id: '143',
    imageNo: 143,
    name: '哈乐餐厅牛肉胡辣汤',
    location: '哈乐餐厅',
    campusLocation: '校内',
    canteen: '其他',
    specificPrice: '¥13',
    priceLevel: PriceLevel.CHEAP,
    tags: ['早餐', '辣', '面食'],
    postDate: '2025-02-18',
    originalUrl: 'https://www.xiaohongshu.com/explore/67b4656e000000002900f071',
    originalPost: '胡辣汤很辣，食材丰富。油条包子中规中矩。冬天喝完很热乎。',
    recommendationIndex: 7.8,
    rating: 3.9
  },
  {
    id: '144',
    imageNo: 144,
    name: '一餐水果店烤红薯',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥6.9 (称重)',
    priceLevel: PriceLevel.CHEAP,
    tags: ['小吃', '甜点'],
    postDate: '2024-12-18',
    originalUrl: 'https://www.xiaohongshu.com/explore/6762c9730000000014025ddc',
    originalPost: '香甜不噎人，表皮带点焦香。冷冬里的幸福感来源。',
    recommendationIndex: 9.0,
    rating: 4.5
  },
  {
    id: '145',
    imageNo: 145,
    name: '思源门外兰溪牛肉面',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '¥17.5',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '辣', '家常菜'],
    postDate: '2024-12-12',
    originalUrl: 'https://www.xiaohongshu.com/explore/675ac529000000000600f488',
    originalPost: '炒面锅气十足，汤面浇头香汤浓。面条纯手工，口感硬弹有嚼劲。',
    recommendationIndex: 9.2,
    rating: 4.6
  },
  {
    id: '146',
    imageNo: 146,
    name: '二餐三楼绿园排骨煲',
    location: '二餐三楼',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥16',
    priceLevel: PriceLevel.CHEAP,
    tags: ['米饭', '砂锅', '辣'],
    postDate: '2024-12-11',
    originalUrl: 'https://www.xiaohongshu.com/explore/6759a38e000000000600e04a',
    originalPost: '酱汁浓郁微辣，排骨软硬适中。里面豆皮吸满汤汁超级入味。',
    recommendationIndex: 8.4,
    rating: 4.2
  },
  {
    id: '147',
    imageNo: 147,
    name: 'DQ圣诞树冰淇淋',
    location: '一餐DQ',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥36',
    priceLevel: PriceLevel.MODERATE,
    tags: ['甜点', '冰淇淋'],
    postDate: '2024-12-16',
    originalUrl: 'https://www.xiaohongshu.com/explore/675fdee4000000001301911a',
    originalPost: '外观漂亮，抹茶粉中和甜腻。含蛋糕粒和麻薯，口感丰富。',
    recommendationIndex: 9.0,
    rating: 4.5
  },
  {
    id: '148',
    imageNo: 148,
    name: '二餐一楼青花椒鱼粉',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥14',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '辣', '一人食'],
    postDate: '2024-12-04',
    originalUrl: 'https://www.xiaohongshu.com/explore/675071c7000000000703b2e8',
    originalPost: '汤底麻麻微辣。粉很弹有嚼劲。鸡肉和豆腐口感都很嫩。',
    recommendationIndex: 8.0,
    rating: 4.0
  },
  {
    id: '149',
    imageNo: 149,
    name: '三餐一楼瓦香鸡',
    location: '三餐一楼',
    campusLocation: '校内',
    canteen: '三餐',
    specificPrice: '¥15',
    priceLevel: PriceLevel.CHEAP,
    tags: ['米饭', '辣', '快餐'],
    postDate: '2024-12-07',
    originalUrl: 'https://www.xiaohongshu.com/explore/67546e99000000000600d940',
    originalPost: '洋葱超多，鸡肉偏少且略干。土豆片入味。整体性价比略低。',
    recommendationIndex: 6.0,
    rating: 3.0
  },
  {
    id: '150',
    imageNo: 150,
    name: '四餐一楼排骨/酥肉煲',
    location: '四餐一楼',
    campusLocation: '校内',
    canteen: '四餐',
    specificPrice: '¥18',
    priceLevel: PriceLevel.CHEAP,
    tags: ['米饭', '砂锅', '辣'],
    postDate: '2024-12-05',
    originalUrl: 'https://www.xiaohongshu.com/explore/6751c490000000000703b3c1',
    originalPost: '排骨煲肉多脱骨。酥肉煲数量可观。汤汁下饭。',
    recommendationIndex: 8.8,
    rating: 4.4
  },
  {
    id: '151',
    imageNo: 151,
    name: '御陕坊香香凉皮',
    location: '思源门外',
    campusLocation: '校外',
    tags: ['面食', '小吃', '辣', '西北菜'],
    postDate: '2024-12-02',
    originalUrl: 'https://www.xiaohongshu.com/explore/674dd2190000000007030ccc',
    originalPost: '凉皮嚼劲爽滑，辣椒油极香。配上麻酱很开胃。',
    recommendationIndex: 9.2,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.6
  },
  {
    id: '152',
    imageNo: 152,
    name: '思源门外潮汕汤面',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '¥25 (双拼饭)',
    priceLevel: PriceLevel.MODERATE,
    tags: ['面食', '米饭', '潮汕菜', '清淡', '烧腊'],
    postDate: '2024-11-23',
    originalUrl: 'https://www.xiaohongshu.com/explore/6741f8f70000000007026ac3',
    originalPost: '猪脚软烂烧鸭甜口，双拼饭超下饭。粿条口感清淡。',
    recommendationIndex: 8.0,
    rating: 4.0
  },
  {
    id: '153',
    imageNo: 153,
    name: '高麦卷饼',
    location: '交大内高麦',
    campusLocation: '校内',
    canteen: '其他',
    specificPrice: '¥12',
    priceLevel: PriceLevel.CHEAP,
    tags: ['夜宵', '小吃', '快餐'],
    postDate: '2024-11-13',
    originalUrl: 'https://www.xiaohongshu.com/explore/6734bcae000000001a01faba',
    originalPost: '卤肉千张入味，晚上吃淀粉肠和炸物非常幸福。',
    recommendationIndex: 8.2,
    rating: 4.1
  },
  {
    id: '154',
    imageNo: 154,
    name: '三餐一楼茴香水饺',
    location: '三餐一楼',
    campusLocation: '校内',
    canteen: '三餐',
    specificPrice: '¥11',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '小吃'],
    postDate: '2024-11-08',
    originalUrl: 'https://www.xiaohongshu.com/explore/672e0a94000000001901a52a',
    originalPost: '茴香馅不错，水饺蘸麻酱非常香，性价比高。',
    recommendationIndex: 8.4,
    rating: 4.2
  },
  {
    id: '155',
    imageNo: 155,
    name: '山东饭店辣子鸡',
    location: '交大附近',
    campusLocation: '校外',
    specificPrice: '人均 ¥70',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['聚餐', '辣', '鲁菜', '家常菜'],
    postDate: '2024-11-09',
    originalUrl: 'https://www.xiaohongshu.com/explore/672f8626000000001a01eaf5',
    originalPost: '分量巨大。辣子鸡浓郁超辣但肉不柴。猪头肉必点。',
    recommendationIndex: 8.6,
    rating: 4.3
  },
  {
    id: '156',
    imageNo: 156,
    name: '二餐西餐厅烤盘饭',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥25',
    priceLevel: PriceLevel.MODERATE,
    tags: ['米饭', '烧烤', '一人食'],
    postDate: '2024-11-06',
    originalUrl: 'https://www.xiaohongshu.com/explore/672b8e7f000000001901af5b',
    originalPost: '烧烤口味的拌饭，茄子油润香甜，称重计费。',
    recommendationIndex: 8.0,
    rating: 4.0
  },
  {
    id: '157',
    imageNo: 157,
    name: '五餐香菇馄饨',
    location: '五餐东湖面馆',
    campusLocation: '校内',
    canteen: '五餐',
    specificPrice: '¥12',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '清淡', '小吃'],
    postDate: '2024-11-04',
    originalUrl: 'https://www.xiaohongshu.com/explore/6728e998000000001901537a',
    originalPost: '清淡首选。皮薄馅有脆感，紫菜酱油汤底中规中矩。',
    recommendationIndex: 7.6,
    rating: 3.8
  },
  {
    id: '158',
    imageNo: 158,
    name: '四餐手撕鸡饭',
    location: '四餐fit+',
    campusLocation: '校内',
    canteen: '四餐',
    specificPrice: '¥13',
    priceLevel: PriceLevel.CHEAP,
    tags: ['米饭', '轻食', '快餐', '减脂'],
    postDate: '2024-10-31',
    originalUrl: 'https://www.xiaohongshu.com/explore/67239f28000000001b02d86c',
    originalPost: '预制菜口感一般。鸡丝微辣，配蒸蛋还可以。',
    recommendationIndex: 6.4,
    rating: 3.2
  },
  {
    id: '159',
    imageNo: 159,
    name: '思源门外猪肝面',
    location: '大田大排面',
    campusLocation: '校外',
    specificPrice: '¥9.9',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '便宜', '一人食'],
    postDate: '2024-10-30',
    originalUrl: 'https://www.xiaohongshu.com/explore/672245f1000000001b02d6d7',
    originalPost: '9.9元巨量猪肝！现炒嫩滑，酱香浓郁，性价比惊人。',
    recommendationIndex: 9.0,
    rating: 4.5
  },
  {
    id: '160',
    imageNo: 160,
    name: '嗨吃江湖烤鱼',
    location: '思源门外',
    campusLocation: '校外',
    tags: ['烤鱼', '聚餐', '辣', '川菜'],
    postDate: '2024-10-28',
    originalUrl: 'https://www.xiaohongshu.com/explore/671fb20600000000240170ce',
    originalPost: '清江鱼刺少口感好，香辣味汤底香。环境治愈。',
    recommendationIndex: 8.8,
    priceLevel: PriceLevel.MODERATE,
    rating: 4.4
  },
  {
    id: '161',
    imageNo: 161,
    name: '一餐酱香饼+粥',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥3.5',
    priceLevel: PriceLevel.CHEAP,
    tags: ['早餐', '便宜', '小吃'],
    postDate: '2024-10-26',
    originalUrl: 'https://www.xiaohongshu.com/explore/671c9792000000002401b5cb',
    originalPost: '简单对付。饼干硬，小米粥甜丝丝。非常便宜。',
    recommendationIndex: 7.0,
    rating: 3.5
  },
  {
    id: '162',
    imageNo: 162,
    name: '七餐寿喜锅',
    location: '七餐西餐厅',
    campusLocation: '校内',
    canteen: '七餐',
    specificPrice: '¥39',
    priceLevel: PriceLevel.MODERATE,
    tags: ['火锅', '聚餐', '日料'],
    postDate: '2024-10-22',
    originalUrl: 'https://www.xiaohongshu.com/explore/6717c77a0000000021006a20',
    originalPost: '食材丰富有肥牛等。汤底偏甜，适合姐妹聊天。',
    recommendationIndex: 7.0,
    rating: 3.5
  },
  {
    id: '163',
    imageNo: 163,
    name: '二餐三楼乌鸡汤',
    location: '二餐三楼',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥26.5',
    priceLevel: PriceLevel.MODERATE,
    tags: ['汤', '养生'],
    postDate: '2024-10-22',
    originalUrl: 'https://www.xiaohongshu.com/explore/6717879d0000000021007b4e',
    originalPost: '性价比极低。汤虽好但胡萝卜喧宾夺主，缺乏肉量。',
    recommendationIndex: 4.0,
    rating: 2.0
  },
  {
    id: '164',
    imageNo: 164,
    name: '九咔米澜炸酱米线',
    location: '外卖',
    campusLocation: '校外',
    specificPrice: '¥20+',
    priceLevel: PriceLevel.MODERATE,
    tags: ['外卖', '面食', '辣', '快餐'],
    postDate: '2024-10-20',
    originalUrl: 'https://www.xiaohongshu.com/explore/6714dafe0000000026034e3d',
    originalPost: '酸辣开胃，汤底好喝。米线滑溜，建议加配菜。',
    recommendationIndex: 8.2,
    rating: 4.1
  },
  {
    id: '165',
    imageNo: 165,
    name: '五餐二楼烤鱼',
    location: '五餐二楼',
    campusLocation: '校内',
    canteen: '五餐',
    specificPrice: '¥18',
    priceLevel: PriceLevel.CHEAP,
    tags: ['烤鱼', '辣', '一人食'],
    postDate: '2024-10-19',
    originalUrl: 'https://www.xiaohongshu.com/explore/6713b14d00000000240192d6',
    originalPost: '分带汤和旋转两种。肉质紧实刺少。香辣味带感。',
    recommendationIndex: 8.6,
    rating: 4.3
  },
  {
    id: '166',
    imageNo: 166,
    name: '玉兰苑煎饼',
    location: '玉兰苑',
    campusLocation: '校内',
    canteen: '玉兰苑',
    tags: ['小吃', '早餐', '便宜'],
    postDate: '2024-10-16',
    originalUrl: 'https://www.xiaohongshu.com/explore/670fd57e000000002401a262',
    originalPost: '很大一个。饼皮焦香薄脆。搭配甄嬛传食用幸福感翻倍。',
    recommendationIndex: 8.4,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.2
  },
  {
    id: '167',
    imageNo: 167,
    name: '一餐冒肥肠',
    location: '一餐二楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥18',
    priceLevel: PriceLevel.CHEAP,
    tags: ['小吃', '辣', '川菜'],
    postDate: '2024-10-10',
    originalUrl: 'https://www.xiaohongshu.com/explore/6707e884000000001a0214ea',
    originalPost: '肥肠软烂处理得干净。口味不错但肉量太少。',
    recommendationIndex: 7.4,
    rating: 3.7
  },
  {
    id: '168',
    imageNo: 168,
    name: '一餐南昌拌粉',
    location: '一餐二楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥13',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '辣', '一人食'],
    postDate: '2024-10-08',
    originalUrl: 'https://www.xiaohongshu.com/explore/67055532000000001902fde8',
    originalPost: '粉条Q弹。包裹肉酱酸菜，微辣浓郁。强烈安利。',
    recommendationIndex: 9.2,
    rating: 4.6
  },
  {
    id: '169',
    imageNo: 169,
    name: '四餐水煮瘦肉片',
    location: '四餐一楼',
    campusLocation: '校内',
    canteen: '四餐',
    specificPrice: '¥15',
    priceLevel: PriceLevel.CHEAP,
    tags: ['川菜', '辣', '米饭'],
    postDate: '2024-10-09',
    originalUrl: 'https://www.xiaohongshu.com/explore/6706a7e3000000001a02101f',
    originalPost: '肉片超嫩！淋油过程治愈。内含年糕片等多种配料。',
    recommendationIndex: 8.6,
    rating: 4.3
  },
  {
    id: '170',
    imageNo: 170,
    name: '一餐酸辣粉/燃面',
    location: '一餐二楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥12/¥13',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '辣', '一人食'],
    postDate: '2024-09-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/66f3eb8e000000001902e503',
    originalPost: '酸辣粉爽滑。燃面偏咸，个人更爱酸辣粉。',
    recommendationIndex: 7.8,
    rating: 3.9
  },
  {
    id: '171',
    imageNo: 171,
    name: '四餐笋尖米粉/鸡排',
    location: '四餐一楼',
    campusLocation: '校内',
    canteen: '四餐',
    specificPrice: '¥10/¥13',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '小吃', '便宜'],
    postDate: '2024-09-28',
    originalUrl: 'https://www.xiaohongshu.com/explore/66f82597000000001902e0c2',
    originalPost: '笋尖米粉四年最爱，加麻酱超香。大鸡排刚出锅脆嫩。',
    recommendationIndex: 9.4,
    rating: 4.7
  },
  {
    id: '172',
    imageNo: 172,
    name: '二餐金枪鱼拌饭',
    location: '二餐西餐厅',
    campusLocation: '校内',
    canteen: '二餐',
    specificPrice: '¥18',
    priceLevel: PriceLevel.CHEAP,
    tags: ['米饭', '一人食'],
    postDate: '2024-09-23',
    originalUrl: 'https://www.xiaohongshu.com/explore/66f16766000000001902e879',
    originalPost: '避雷。质量严重下滑。肉少腥味重。大踩雷。',
    recommendationIndex: 3.0,
    rating: 1.5
  },
  {
    id: '173',
    imageNo: 173,
    name: '御陕坊油泼扯面',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '¥22',
    priceLevel: PriceLevel.MODERATE,
    tags: ['面食', '辣', '西北菜', '一人食'],
    postDate: '2024-09-22',
    originalUrl: 'https://www.xiaohongshu.com/explore/66eef2960000000012012377',
    originalPost: '面条筋道。辣椒极香但不辣。量足，常需拼桌。',
    recommendationIndex: 9.4,
    rating: 4.7
  },
  {
    id: '174',
    imageNo: 174,
    name: '海宁煲红烧肉',
    location: '思源门外',
    campusLocation: '校外',
    specificPrice: '¥75 (总额)',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['家常菜', '聚餐', '米饭'],
    postDate: '2024-09-19',
    originalUrl: 'https://www.xiaohongshu.com/explore/66ec35e9000000000c01aee2',
    originalPost: '肉炖得软烂入味，甜咸适中超下饭。土豆软糯。',
    recommendationIndex: 8.6,
    rating: 4.3
  },
  {
    id: '175',
    imageNo: 175,
    name: '一餐碗杂面',
    location: '一餐二楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥12',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '辣', '一人食'],
    postDate: '2024-09-19',
    originalUrl: 'https://www.xiaohongshu.com/explore/66eb8bfc000000000c019d90',
    originalPost: '酱香浓郁加一点点辣。黄豆软绵。分量略少但解馋。',
    recommendationIndex: 8.8,
    rating: 4.4
  },
  {
    id: '176',
    imageNo: 176,
    name: '七餐日式烧肉饭',
    location: '七餐西餐厅',
    campusLocation: '校内',
    canteen: '七餐',
    specificPrice: '¥38',
    priceLevel: PriceLevel.MODERATE,
    tags: ['日料', '米饭', '聚餐'],
    postDate: '2024-09-18',
    originalUrl: 'https://www.xiaohongshu.com/explore/66ea2b61000000001e01bc7c',
    originalPost: '酱汁浓郁。温泉蛋和肉拌米饭口感丰富。价格在校内偏贵。',
    recommendationIndex: 8.0,
    rating: 4.0
  },
  {
    id: '177',
    imageNo: 177,
    name: '紫燕百味鸡拌面',
    location: '外卖',
    campusLocation: '校外',
    tags: ['外卖', '小吃', '凉菜', '辣'],
    postDate: '2024-10-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/6694a1560000000025014674',
    originalPost: '藤椒鸡凉拌面是夏天绝配。汤汁裹满面条超爽口。',
    recommendationIndex: 8.6,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.3
  },
  {
    id: '178',
    imageNo: 178,
    name: '一餐肉酱酸辣粉',
    location: '一餐二楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ["面食", "辣", "一人食"],
    postDate: '2024-07-06',
    originalUrl: 'https://www.xiaohongshu.com/explore/66889bc5000000001c025f41',
    originalPost: '粉很筋道久不坨。汤底浓郁咸辣香。爱里面的酸菜。',
    recommendationIndex: 8.2,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.1
  },
  {
    id: '179',
    imageNo: 179,
    name: '一餐鸡丝拌面',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['面食', '凉菜', '辣'],
    postDate: '2024-05-19',
    originalUrl: 'https://www.xiaohongshu.com/explore/6649619b00000000160104d8',
    originalPost: '筋道爽滑。酸辣调料很开胃不腻。适合闷热的中午。',
    recommendationIndex: 7.6,
    priceLevel: PriceLevel.CHEAP,
    rating: 3.8
  },
  {
    id: '180',
    imageNo: 180,
    name: '一餐鱼香肉丝饭',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['米饭', '家常菜', '一人食'],
    postDate: '2024-05-07',
    originalUrl: 'https://www.xiaohongshu.com/explore/6639b3c0000000001e033044',
    originalPost: '鲜嫩爽滑带甜口。菜量大下饭。米饭口感不错。',
    recommendationIndex: 7.8,
    priceLevel: PriceLevel.CHEAP,
    rating: 3.9
  },
  {
    id: '181',
    imageNo: 181,
    name: '四餐烧鸭饭',
    location: '四餐一楼',
    campusLocation: '校内',
    canteen: '四餐',
    tags: ['米饭', '烧腊', '清淡'],
    postDate: '2024-04-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/662a3f080000000001032b24',
    originalPost: '清淡健康。鸭皮脆甜带油脂。卤汁拌饭无敌。',
    recommendationIndex: 8.8,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.4
  },
  {
    id: '182',
    imageNo: 182,
    name: '二餐麻辣拌面',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    tags: ['小吃', '辣', '一人食'],
    postDate: '2024-04-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/6629dbe10000000001007a4d',
    originalPost: '方便面面饼入味，加花生碎口感好。微辣也很辣。',
    recommendationIndex: 7.6,
    priceLevel: PriceLevel.CHEAP,
    rating: 3.8
  },
  {
    id: '183',
    imageNo: 183,
    name: '四餐蔬菜冒菜',
    location: '四餐一楼',
    campusLocation: '校内',
    canteen: '四餐',
    tags: ['清淡', '一人食', '养生', '减脂'],
    postDate: '2024-04-22',
    originalUrl: 'https://www.xiaohongshu.com/explore/662623d7000000000100555e',
    originalPost: '荤素称重。蔬菜多但味道一般。偶尔补菜首选。',
    recommendationIndex: 5.0,
    priceLevel: PriceLevel.CHEAP,
    rating: 2.5
  },
  {
    id: '184',
    imageNo: 184,
    name: '二餐一楼鸡公煲',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    tags: ['砂锅', '辣', '米饭'],
    postDate: '2024-04-21',
    originalUrl: 'https://www.xiaohongshu.com/explore/662475f6000000000401a5d0',
    originalPost: '香气足。鸡肉量尚可但边角料多。麻味突出。',
    recommendationIndex: 7.2,
    priceLevel: PriceLevel.CHEAP,
    rating: 3.6
  },
  {
    id: '185',
    imageNo: 185,
    name: '玉兰苑鸡蛋灌饼',
    location: '玉兰苑',
    campusLocation: '校内',
    canteen: '玉兰苑',
    tags: ['小吃', '早餐', '便宜'],
    postDate: '2024-04-15',
    originalUrl: 'https://www.xiaohongshu.com/explore/661c8a6e000000001a012e85',
    originalPost: '蛋香油香。烙后烘烤外酥里松。卷生菜鸡柳口感丰富。',
    recommendationIndex: 9.6,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.8
  },
  {
    id: '186',
    imageNo: 186,
    name: '一餐香辣牛肉面',
    location: '一餐二楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['面食', '辣', '一人食'],
    postDate: '2024-04-14',
    originalUrl: 'https://www.xiaohongshu.com/explore/661aae72000000001a00e579',
    originalPost: '麻辣酱香交织。面条吸满汤汁。牛肉少但入味。',
    recommendationIndex: 8.4,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.2
  },
  {
    id: '187',
    imageNo: 187,
    name: '一餐土鸡小面',
    location: '一餐二楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['面食', '养生', '清淡'],
    postDate: '2024-04-09',
    originalUrl: 'https://www.xiaohongshu.com/explore/66154903000000001a00c7f5',
    originalPost: '安心的鸡汤味，肉骨酥烂。面入味。适合养胃时刻。',
    recommendationIndex: 8.6,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.3
  },
  {
    id: '188',
    imageNo: 188,
    name: '三餐石锅拌饭',
    location: '三餐二楼',
    campusLocation: '校内',
    canteen: '三餐',
    tags: ['米饭', '辣', '一人食'],
    postDate: '2024-04-08',
    originalUrl: 'https://www.xiaohongshu.com/explore/66140d71000000001a010beb',
    originalPost: '滋啦响的幸福感。土豆泥拌入。比二餐的口味更热情。',
    recommendationIndex: 8.6,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.3
  },
  {
    id: '189',
    imageNo: 189,
    name: '三餐红油拌粉',
    location: '三餐二楼',
    campusLocation: '校内',
    canteen: '三餐',
    tags: ['面食', '辣', '一人食'],
    postDate: '2024-04-08',
    originalUrl: 'https://www.xiaohongshu.com/explore/6613bfd4000000001a013fde',
    originalPost: '有韧性爽滑。酸菜酱油味重，越吃越爱。',
    recommendationIndex: 9.0,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.5
  },
  {
    id: '190',
    imageNo: 190,
    name: '二餐麻辣香锅',
    location: '二餐三楼',
    campusLocation: '校内',
    canteen: '二餐',
    tags: ['辣', '聚餐', '一人食'],
    postDate: '2024-04-07',
    originalUrl: 'https://www.xiaohongshu.com/explore/661276e4000000001a01128a',
    originalPost: '中规中矩。适合补菜。辣味咸淡适宜，不容易上火。',
    recommendationIndex: 6.0,
    priceLevel: PriceLevel.CHEAP,
    rating: 3.0
  },
  {
    id: '191',
    imageNo: 191,
    name: '你六姐冒菜',
    location: '龙湖天街',
    campusLocation: '校外',
    tags: ['火锅', '辣', '聚餐', '川菜'],
    postDate: '2024-10-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/660e66be000000001a0149e5',
    originalPost: '自选菜种类多。油碟配蒜泥绝。免费冰粉解辣。',
    recommendationIndex: 8.4,
    priceLevel: PriceLevel.MODERATE,
    rating: 4.2
  },
  {
    id: '192',
    imageNo: 192,
    name: '二餐一楼豆腐脑',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    tags: ['早餐', '甜点', '小吃'],
    postDate: '2024-04-03',
    originalUrl: 'https://www.xiaohongshu.com/explore/660cb294000000001a00ef42',
    originalPost: '甜口的口感细腻。淡淡豆香加糖，春早里的幸福感。',
    recommendationIndex: 9.2,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.6
  },
  {
    id: '193',
    imageNo: 193,
    name: '一餐一楼印度飞饼',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['小吃', '甜点'],
    postDate: '2024-04-02',
    originalUrl: 'https://www.xiaohongshu.com/explore/660b823c000000001a00e204',
    originalPost: '香蕉味甜。外酥里绵。适合饭后甜点。',
    recommendationIndex: 8.0,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.0
  },
  {
    id: '194',
    imageNo: 194,
    name: '一餐一楼炸酱面',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    specificPrice: '¥7 (小份)',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '便宜', '一人食'],
    postDate: '2024-04-01',
    originalUrl: 'https://www.xiaohongshu.com/explore/660a9c73000000001a0156b9',
    originalPost: '酱香浓郁厚重。小份也很饱。口味略重。',
    recommendationIndex: 7.6,
    rating: 3.8
  },
  {
    id: '195',
    imageNo: 195,
    name: '阿姨炒饭',
    location: '外卖',
    campusLocation: '校外',
    tags: ['外卖', '米饭', '快餐', '家常菜'],
    postDate: '2024-03-31',
    originalUrl: 'https://www.xiaohongshu.com/explore/66097d32000000001a01356c',
    originalPost: '溏心蛋是灵魂。蛋液拌饭中和了腻感，色彩迷人。',
    recommendationIndex: 8.6,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.3
  },
  {
    id: '196',
    imageNo: 196,
    name: '五餐一楼石锅鸡块',
    location: '五餐一楼',
    campusLocation: '校内',
    canteen: '五餐',
    tags: ["米饭", "咸", "一人食"],
    postDate: '2024-03-28',
    originalUrl: 'https://www.xiaohongshu.com/explore/6604d3a8000000001203c41a',
    originalPost: '石锅现制，加蛋版最好。料汁极咸。吃完有味道。',
    recommendationIndex: 7.4,
    priceLevel: PriceLevel.CHEAP,
    rating: 3.7
  },
  {
    id: '197',
    imageNo: 197,
    name: '二餐一楼啫啫煲',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    tags: ['砂锅', '米饭', '一人食'],
    postDate: '2024-03-28',
    originalUrl: 'https://www.xiaohongshu.com/explore/660533b5000000001202048b',
    originalPost: '啫啫肥牛酱香浓郁，配菜藕片软糯。制作久需等待。',
    recommendationIndex: 8.0,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.0
  },
  {
    id: '198',
    imageNo: 198,
    name: '二餐韩式炸鸡拌饭',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    tags: ['米饭', '韩式', '一人食'],
    postDate: '2024-03-29',
    originalUrl: 'https://www.xiaohongshu.com/explore/6606b2d6000000001a013a36',
    originalPost: '锅巴焦香。炸鸡块大但口感略干。配菜清爽平衡。',
    recommendationIndex: 8.2,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.1
  },
  {
    id: '199',
    imageNo: 199,
    name: '一餐一楼飘香鸡',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['米饭', '辣', '快餐'],
    postDate: '2024-03-27',
    originalUrl: 'https://www.xiaohongshu.com/explore/6603dd160000000012022846',
    originalPost: '一餐元老。鸡肉香辣表皮脆。土豆软糯是亮点。',
    recommendationIndex: 8.4,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.2
  },
  {
    id: '200',
    imageNo: 200,
    name: '二餐一楼建德炒粉',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    tags: ['面食', '辣', '一人食'],
    postDate: '2024-03-22',
    originalUrl: 'https://www.xiaohongshu.com/explore/65fcfbc6000000001203d89c',
    originalPost: '猛火快炒带迷人焦香。粉粗滑嫩入味。配料足。',
    recommendationIndex: 8.0,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.0
  },
  {
    id: '201',
    imageNo: 201,
    name: '二餐香辣排骨米线',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    tags: ['面食', '辣', '一人食'],
    postDate: '2024-03-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/660187720000000012023809',
    originalPost: '香辣度高且量大。排骨都是精华段位。极力推荐给辣党。',
    recommendationIndex: 8.8,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.4
  },
  {
    id: '202',
    imageNo: 202,
    name: '一餐一楼牛杂煲',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['砂锅', '辣', '米饭'],
    postDate: '2024-03-18',
    originalUrl: 'https://www.xiaohongshu.com/explore/65f7bd6c000000000d00d755',
    originalPost: '辣味去腥。牛杂软烂不柴，豆腐千张下饭。吃到最后很烫。',
    recommendationIndex: 8.2,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.1
  },
  {
    id: '203',
    imageNo: 203,
    name: '思源门外鸡公煲',
    location: '思源门外',
    campusLocation: '校外',
    tags: ['砂锅', '辣', '校外', '米饭'],
    postDate: '2024-03-13',
    originalUrl: 'https://www.xiaohongshu.com/explore/65f1b5b2000000001202023b',
    originalPost: '鸡肉鲜嫩加方便面是绝配。比校内酱香更浓。衣服易留味。',
    recommendationIndex: 8.4,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.2
  },
  {
    id: '204',
    imageNo: 204,
    name: '一餐二楼豆花烤鱼',
    location: '一餐二楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['烤鱼', '辣', '一人食'],
    postDate: '2024-03-11',
    originalUrl: 'https://www.xiaohongshu.com/explore/65ee78c8000000001203ff9d',
    originalPost: '豆花吸满香辣汤底，无敌下饭。鱼刺少可放心食用。',
    recommendationIndex: 9.0,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.5
  },
  {
    id: '205',
    imageNo: 205,
    name: '二餐咖喱蛋包饭',
    location: '二餐一楼',
    campusLocation: '校内',
    canteen: '二餐',
    tags: ['米饭', '日料', '一人食'],
    postDate: '2024-03-12',
    originalUrl: 'https://www.xiaohongshu.com/explore/65f06a84000000000d00c382',
    originalPost: '嫩滑鸡蛋加鸡米花。火候完美。虽然辛香味少，但视觉冲击满分。',
    recommendationIndex: 8.0,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.0
  },
  {
    id: '206',
    imageNo: 206,
    name: '一餐滋补鸡汤面',
    location: '一餐一楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['面食', '清淡', '养生'],
    postDate: '2024-03-12',
    originalUrl: 'https://www.xiaohongshu.com/explore/65efb1a5000000001203ddd8',
    originalPost: '清淡首选。汤鲜肉入味，枸杞红枣有形式上的养生感。',
    recommendationIndex: 8.6,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.3
  },
  {
    id: '207',
    imageNo: 207,
    name: '环院创咖吐司冰淇淋',
    location: '环境学院',
    campusLocation: '校内',
    canteen: '其他',
    specificPrice: '¥3.5',
    priceLevel: PriceLevel.CHEAP,
    tags: ['甜点', '便宜', '小吃'],
    postDate: '2024-04-17',
    originalUrl: 'https://www.xiaohongshu.com/explore/65ed41e0000000000d00c478',
    originalPost: '冷热麦奶香碰撞。💯昏甜品。只需3.5元太适合春天。',
    recommendationIndex: 9.8,
    rating: 4.9
  },
  {
    id: '208',
    imageNo: 208,
    name: '一餐二楼红油抄手',
    location: '一餐二楼',
    campusLocation: '校内',
    canteen: '一餐',
    tags: ['面食', '辣', '小吃'],
    postDate: '2024-03-10',
    originalUrl: 'https://www.xiaohongshu.com/explore/65ed9260000000000d00c1d1',
    originalPost: '油亮开胃。鲜嫩馅料加香辣辣椒油绝配。建议蘸汤吃。',
    recommendationIndex: 9.0,
    priceLevel: PriceLevel.CHEAP,
    rating: 4.5
  }
];