import { FoodItem, PriceLevel } from './types';

export const INITIAL_FOODS: FoodItem[] = [
  {
    id: '101',
    imageNo: 101,
    name: '御陕坊猪头肉拌饭/水饺',
    location: '交大食堂 (御陕坊)',
    priceLevel: PriceLevel.MODERATE,
    tags: ['食堂', '面食', '猪肉'],
    rating: 4.8,
    postDate: '01-08',
    originalUrl: 'https://www.xiaohongshu.com/explore/695f8348000000001a036167?xsec_token=ABKZk4nxQus0ZUEPnzzAllKNpgsxWh-wqbfnvj129755U=&xsec_source=pc_user',
    originalPost: "猪头肉非常软烂！猪肝香香的 麻辣香肠香香辣辣。和一点点黄瓜香菜拌在一起绝了啊。之后打包去山东水饺吃饺子，饺子蘸拌菜的汤汁也好绝啊。",
    recommendationIndex: 9
  },
  {
    id: '102',
    imageNo: 102,
    name: '漂亮云南咖啡店',
    location: '交大校内',
    priceLevel: PriceLevel.MODERATE,
    tags: ['甜点', '咖啡', '云南菜', '下午茶'],
    rating: 4.3,
    postDate: '2025-12-01',
    originalUrl: 'https://www.xiaohongshu.com/explore/692d0e15000000001e02b2c9?xsec_token=ABCA34LlbKlleRwDVNSS0ltzIXcqNabzLK9thsXwJegCY=&xsec_source=pc_user',
    originalPost: "一家咖啡店但有很多特色云南菜以及简餐。环境很漂亮！甜食🍰很喜欢。感觉很适合点饮料和小蛋糕然后坐在这边自习。",
    recommendationIndex: 8
  },
  {
    id: '103',
    imageNo: 103,
    name: '红旗羊肉',
    location: '交大食堂',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['食堂', '羊肉', '火锅', '聚餐'],
    rating: 4.9,
    postDate: '2025-03-09',
    originalUrl: 'https://www.xiaohongshu.com/explore/67cdacea000000002902c356?xsec_token=ABp-MuV14kXHVZ4uLWFq_sf3ssKh8-PpDyVaWPVPQ4sFo=&xsec_source=pc_user',
    originalPost: "肉炖的软烂 很香但个人觉得一点都不膻。蘸上酱油+辣椒油香绝了！皮口感也很好 滑溜溜的但不腻。还点了一碗葱油拌面也很便宜好吃。",
    recommendationIndex: 9.5
  },
  {
    id: '104',
    imageNo: 104,
    name: '二餐石锅鸡',
    location: '二餐一楼 (吉祥馄饨旁)',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '快餐', '辣', '鸡肉'],
    rating: 4.6,
    postDate: '2025-11-26',
    originalUrl: 'https://www.xiaohongshu.com/explore/69253bc6000000001e036ca5?xsec_token=ABXT_4DSXaEKelLFa6Rf1OdoSvo_vZ-O0j6RHrcJogr_Y=&xsec_source=pc_user',
    originalPost: "点了干锅鸡微辣加炸蛋，汤底香香辣辣的！炸蛋蘸满汤汁绝了。鸡肉很嫩且并非边角部位。配料有白菜土豆粉丝粉皮还有少许方便面。",
    recommendationIndex: 9
  },
  {
    id: '105',
    imageNo: 105,
    name: '牛new大闸蟹寿喜锅',
    location: '牛new',
    priceLevel: PriceLevel.LUXURY,
    tags: ['火锅', '大闸蟹', '日料', '自助'],
    rating: 5.0,
    postDate: '2025-10-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/68fc7a9c0000000004000850?xsec_token=ABIL3uMeu13N3a6A6J5VYmaIpPazqeTTPQTS4EX2F1Oag=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "2.5两母蟹个个满黄！大块蟹黄沾点蟹醋香绝了。清水+寿喜锅双拼锅底，等待蟹煮熟的时间可以寿喜锅涮牛肉也好好吃🤤。",
    recommendationIndex: 10
  },
  {
    id: '106',
    imageNo: 106,
    name: '二餐辛拉面',
    location: '二餐一楼',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '面食', '韩式'],
    rating: 3.8,
    postDate: '2025-12-12',
    originalUrl: 'https://www.xiaohongshu.com/explore/693c34a9000000001e0276c9?xsec_token=ABHt6zP2CXCbOYTu0I-f8MQ6HRCb81p0Eqb-p7yYpujlw=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "好吃但性价比低。汤底是香香的，介于清淡和醇厚之间。辛拉面很弹口感不错！配菜有生菜鱼豆腐以及烤肠。适合冷冷的天气吃。",
    recommendationIndex: 7
  },
  {
    id: '107',
    imageNo: 107,
    name: '四餐大棒骨',
    location: '四餐二楼农家菜',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '家常菜', '肉食'],
    rating: 4.5,
    postDate: '2025-10-27',
    originalUrl: 'https://www.xiaohongshu.com/explore/68ff396d0000000004010342?xsec_token=ABqQVWQrdVQ_n6V4FSkrCgNKO3KqR_ofsm-zFHfxnUeNk=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "巨大一个骨头棒，汤喝起来鲜鲜的。大骨头上面有很多肉，炖的烂烂的一点都不柴。",
    recommendationIndex: 9
  },
  {
    id: '108',
    imageNo: 108,
    name: '俏传奇地锅鸡',
    location: '宝龙广场',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['家常菜', '聚餐', '地锅鸡'],
    rating: 4.7,
    postDate: '2025-11-22',
    originalUrl: 'https://www.xiaohongshu.com/explore/69214eff000000001e037d5f?xsec_token=AB-DfH28rVBFCrxs-9_MTzFxHLcB-0KGoqWULe4QT49Mk=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "现场爆炒后炖煮 掀开锅盖香迷糊了！肉咸咸香香的超软烂入味！菜沾满汤汁很下饭。饼底在锅边烘烤过脆脆的口感好好。",
    recommendationIndex: 9
  },
  {
    id: '109',
    imageNo: 109,
    name: '二餐土豆泥拌饭',
    location: '二餐西餐厅',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '西餐', '简餐'],
    rating: 4.2,
    postDate: '2025-12-27',
    originalUrl: 'https://www.xiaohongshu.com/explore/694f810f000000001f006fe0?xsec_token=ABU8pCtSa9Z0T3JbU38T1EE0DnMHyOXF9ikvTMop6O6iE=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "很多土豆泥，和饭拌在一起香喷喷软绵绵的。鸡排中规中矩。饭真的很好吃！酱略带一点点酸味。",
    recommendationIndex: 8
  },
  {
    id: '110',
    imageNo: 110,
    name: '海底捞番茄汤虾滑捞饭',
    location: '外卖 (海底捞)',
    priceLevel: PriceLevel.MODERATE,
    tags: ['外卖', '火锅', '海鲜'],
    rating: 4.8,
    postDate: '2025-10-03',
    originalUrl: 'https://www.xiaohongshu.com/explore/68dfa2bb000000000400632b?xsec_token=ABRcgan178eh13Pek7l4cFnVYTzDyVj2GYuPcsNGVhal8=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "倒入番茄汤之后搅拌均匀，每一口都是浓郁的番茄香味。虾滑超大颗好好吃！还有玉米粒牛肉粒芹菜粒青豆粒。",
    recommendationIndex: 9
  },
  {
    id: '111',
    imageNo: 111,
    name: '玉兰苑冰淇淋菠萝包',
    location: '玉兰苑',
    priceLevel: PriceLevel.CHEAP,
    tags: ['甜点', '面包', '小吃'],
    rating: 4.4,
    postDate: '2025-09-21',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d0171f000000000b03c3b6?xsec_token=AB39Qy2k25TxqVSRCB8WDXW7Y877vV5FKfFui9fpp7I0Y=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "热乎乎的菠萝包夹着凉丝丝的冰淇淋。酥皮的微咸、面包的麦香和甜甜凉凉的冰淇淋配在一起好好吃🤤。",
    recommendationIndex: 8.5
  },
  {
    id: '112',
    imageNo: 112,
    name: '二餐奥利奥鸡蛋仔',
    location: '二餐一楼 (轻甜茶季)',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '甜点', '小吃'],
    rating: 4.1,
    postDate: '2025-11-27',
    originalUrl: 'https://www.xiaohongshu.com/explore/69272980000000001e0340ae?xsec_token=ABWtdyNkUDMIV-7ylMOSRGFt-_VsWprTt5BtL_ywLCfEM=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "鸡蛋仔好好吃啊，蘸上冰淇淋香香甜甜的。冰淇淋是冰感有点强的那种，好处是不腻。",
    recommendationIndex: 8
  },
  {
    id: '113',
    imageNo: 113,
    name: '成都巷子水煮鱼',
    location: '剑川路',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['川菜', '鱼', '聚餐'],
    rating: 4.6,
    postDate: '2025-05-28',
    originalUrl: 'https://www.xiaohongshu.com/explore/68367c2000000000210055c4?xsec_token=ABd4B8Zu7LHcDvnJt55lKDmeF4sOPPq6eg3_gIV34nUkY=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "鱼是现杀的黑鱼，很新鲜。锅底巨香啊！点了微辣，有淡淡的麻感很上头。配菜浸满汤汁好好吃。",
    recommendationIndex: 9
  },
  {
    id: '114',
    imageNo: 114,
    name: '储牛香潮汕牛肉火锅',
    location: '思源门外',
    priceLevel: PriceLevel.EXPENSIVE,
    tags: ['火锅', '牛肉', '聚餐'],
    rating: 4.9,
    postDate: '2025-12-08',
    originalUrl: 'https://www.xiaohongshu.com/explore/6927e624000000001e0279dc?xsec_token=ABWtdyNkUDMIV-7ylMOSRGFnm7wey3qEu3ONkIuPX8zKE=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "肉都是鲜切的，超新鲜。裹满沙茶酱香绝了，吃牛肉火锅必须配沙茶酱！炒饭也超好吃，锅气好足。",
    recommendationIndex: 9.5
  },
  {
    id: '115',
    imageNo: 115,
    name: '一餐红枣桂圆鸡',
    location: '一餐一楼',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '家常菜', '养生'],
    rating: 4.3,
    postDate: '2025-11-23',
    originalUrl: 'https://www.xiaohongshu.com/explore/6922ea6b000000001e02ef2f?xsec_token=AB6zwZmn5ZOY0CLfdJmUEC4SvCj_7KVadaYGUtmwhAn64=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "暖暖的鸡汤太适合寒冷冬天！依然是大大的鸡腿，热乎乎香香的汤底。鸡腿的肉很软烂一点都不柴。",
    recommendationIndex: 8.5
  },
  {
    id: '116',
    imageNo: 116,
    name: '陈香贵番茄牛骨面',
    location: '校外/连锁',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '快餐'],
    rating: 4.2,
    postDate: '2025-03-20',
    originalUrl: 'https://www.xiaohongshu.com/explore/67daea06000000001d0266ac?xsec_token=ABG_JclqrIsl7Hmslr8Dnh_JUdoJpyaLY-9jl5gKpR-qo=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "番茄牛骨汤面好吃啊，有点像海底捞番茄锅的味道。除了浓郁的番茄酱还加了新鲜番茄，汤也好喝。分量很感人。",
    recommendationIndex: 8
  },
  {
    id: '117',
    imageNo: 117,
    name: '牛new甜品系列',
    location: '牛new',
    priceLevel: PriceLevel.MODERATE,
    tags: ['甜点', '下午茶'],
    rating: 4.5,
    postDate: '2024-10-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/66225be70000000001032cd6?xsec_token=AB1PF0jqPrMIvYR3YzN5WGv8oSRLVsU_yiQlRsxxk8iQ8=&xsec_source=pc_search&source=web_explore_feed',
    originalPost: "强推：焦糖布丁（焦糖脆皮香甜）、巴斯克（浓郁芝士味）、巧克力空气生巧。榴莲大福和萄你欢心也不错！",
    recommendationIndex: 9
  },
  {
    id: '118',
    imageNo: 118,
    name: '西贝小炒牛肉',
    location: '外卖 (西贝)',
    priceLevel: PriceLevel.MODERATE,
    tags: ['外卖', '家常菜'],
    rating: 4.0,
    postDate: '2025-11-07',
    originalUrl: 'https://www.xiaohongshu.com/explore/690d813f0000000005033dfc?xsec_token=ABANQJoF68xrbPZ3vSMcWoNK2-2NE8032cJGz4s-J4U9g=&xsec_source=pc_user',
    originalPost: "牛肉很好吃！嫩嫩的辣辣的很下饭。豆腐汤好喝！很鲜！外卖半价活动时候买很划算。",
    recommendationIndex: 8
  },
  {
    id: '119',
    imageNo: 119,
    name: '二餐徽三鲜',
    location: '二餐三楼',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '家常菜'],
    rating: 3.5,
    postDate: '2025-11-04',
    originalUrl: 'https://www.xiaohongshu.com/explore/690973f00000000004015126?xsec_token=ABp-d7BNfshBFge8F-S78k714v5Btz5yzlUGwJO0V5cUY=&xsec_source=pc_user',
    originalPost: "汤底味道很鲜（但有点咸）。内容很丰富，有鸡丝酥肉蛋饺以及肉片。适合没什么胃口的时候吃一点清淡的。",
    recommendationIndex: 7
  },
  {
    id: '120',
    imageNo: 120,
    name: '思源门河北炒饼',
    location: '思源门外/外卖',
    priceLevel: PriceLevel.CHEAP,
    tags: ['外卖', '面食', '小吃'],
    rating: 4.3,
    postDate: '2025-10-29',
    originalUrl: 'https://www.xiaohongshu.com/explore/6901f7ac000000000400352b?xsec_token=AB_HnrLnkXbn51BgWeGtFQGHPP46WYNjfyiJzmiQKDAwE=&xsec_source=pc_user',
    originalPost: "很好吃！锅气十足，香香辣辣的。配料很丰富，有鸡蛋豆芽包菜以及培根烤肠。建议直接去店里吃，外卖包菜会变软。",
    recommendationIndex: 8.5
  },
  {
    id: '121',
    imageNo: 121,
    name: '四餐鸭血粉丝汤',
    location: '四餐二楼',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '小吃', '面食'],
    rating: 4.2,
    postDate: '2025-10-28',
    originalUrl: 'https://www.xiaohongshu.com/explore/6900ad1c000000000500214f?xsec_token=ABOFpHcY8N4lBJEryDPYQgAzakyZQSQc2IdGOSBnAPhH4=&xsec_source=pc_user',
    originalPost: "汤的味道很浓郁很好喝！鸭血以及各种鸭杂也好吃，粉丝口感刚好。饼酥酥脆脆的。",
    recommendationIndex: 8
  },
  {
    id: '122',
    imageNo: 122,
    name: '四餐大棒骨 (再次推荐)',
    location: '四餐二楼农家菜',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '家常菜', '肉食'],
    rating: 4.5,
    postDate: '2025-10-27',
    originalUrl: 'https://www.xiaohongshu.com/explore/68ff396d0000000004010342?xsec_token=ABqIUnKJwU_076pqTLfXulECEIczvl78tKAhRHLPp3hbI=&xsec_source=pc_user',
    originalPost: "四餐二楼农家菜！巨大一个骨头棒，汤喝起来鲜鲜的。肉炖的烂烂的一点都不柴。",
    recommendationIndex: 9
  },
  {
    id: '123',
    imageNo: 123,
    name: '大田大排面青椒肉丝',
    location: '思源门外',
    priceLevel: PriceLevel.CHEAP,
    tags: ['面食', '快餐'],
    rating: 4.6,
    postDate: '2025-09-25',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d55fcb000000000b03f81b?xsec_token=AB2L4JPChuv8LiInKb2NveJZa9CDxWWFQSC18mYxjqOek=&xsec_source=pc_user',
    originalPost: "现炒的青椒肉丝，肉很嫩很入味，青椒恰到好处的好吃。浓郁的酱香裹满每根面条。",
    recommendationIndex: 9
  },
  {
    id: '124',
    imageNo: 124,
    name: '五餐菌菇鸡汤饭',
    location: '五餐二楼',
    priceLevel: PriceLevel.CHEAP,
    tags: ['食堂', '家常菜', '清淡'],
    rating: 4.0,
    postDate: '2025-09-24',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d3ea82000000000e00d48c?xsec_token=ABsToiQWF8l8Swm_-xixYBsc5oQ0khgV_VYH-sUsgXuC8=&xsec_source=pc_user',
    originalPost: "清澈的鸡汤泡着米饭以及鸡肉菌菇蔬菜。鸡汤很鲜，鸡肉味道清淡但不会很柴。很适合清淡饮食阶段选择暖呼呼的。",
    recommendationIndex: 8
  },
  {
    id: '125',
    imageNo: 125,
    name: '东坡肉焗饭',
    location: '外卖',
    priceLevel: PriceLevel.MODERATE,
    tags: ['外卖', '家常菜'],
    rating: 4.5,
    postDate: '2025-09-23',
    originalUrl: 'https://www.xiaohongshu.com/explore/68d29862000000000e030d65?xsec_token=ABLCNIBqhW3EIMn8_r1Aoq5X_5bvDowV3cAg-uonJXD1Q=&xsec_source=pc_user',
    originalPost: "巨巨巨好吃！一大块软烂的东坡肉和米饭蔬菜拌在一起。米饭沾满油汪汪的东坡肉以及肉汁香绝了。",
    recommendationIndex: 9
  }
];
